'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  FileText, Presentation, Layout, FileDown, 
  Sparkles, Monitor, Type, ArrowRight, Download,
  CheckCircle2, RefreshCw, Palette, Layers, Zap
} from 'lucide-react';
import { cn } from '@/lib/utils';
import pptxgen from 'pptxgenjs';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';

export default function StudioView() {
  const [docType, setDocType] = useState<'pptx' | 'docx'>('pptx');
  const [topic, setTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [generatedFile, setGeneratedFile] = useState<{ name: string, blob: Blob } | null>(null);
  const [template, setTemplate] = useState('professional');
  const [slideCount, setSlideCount] = useState<number>(5);
  const [themeColor, setThemeColor] = useState<string>('3b82f6'); // default blue

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setIsGenerating(true);
    setProgress(10);
    
    // Simulate thinking/generation steps
    await new Promise(r => setTimeout(r, 800));
    setProgress(40);
    await new Promise(r => setTimeout(r, 800));
    setProgress(70);
    
    try {
      if (docType === 'pptx') {
        const pres = new pptxgen();
        pres.layout = 'LAYOUT_16x9';
        
        // Title Slide
        const slide1 = pres.addSlide();
        slide1.background = { color: template === 'dark' ? '1A1A1A' : 'FFFFFF' };
        slide1.addText(topic.toUpperCase(), { 
          x: 1, y: 2, w: '80%', fontSize: 44, bold: true, 
          color: template === 'dark' ? 'FFFFFF' : '000000', align: 'center' 
        });
        slide1.addText("Generated by AI Clone Research Node", { 
          x: 1, y: 3.5, w: '80%', fontSize: 18, 
          color: themeColor, align: 'center' 
        });

        // Content Slides
        for (let i = 2; i <= slideCount; i++) {
          const slide = pres.addSlide();
          slide.background = { color: template === 'dark' ? '1A1A1A' : 'FFFFFF' };
          slide.addText(`Section ${i - 1}: Analysis`, { x: 0.5, y: 0.5, fontSize: 32, bold: true, color: themeColor });
          slide.addText([
            { text: `Data point ${i}.1 derived from global synthesis`, options: { bullet: true, color: template === 'dark' ? 'CCCCCC' : '333333' } },
            { text: `Cross-reference node ${i}.2`, options: { bullet: true, indentLevel: 1, color: template === 'dark' ? 'CCCCCC' : '333333' } },
            { text: `Extrapolated metrics for section ${i}`, options: { bullet: true, color: template === 'dark' ? 'CCCCCC' : '333333' } }
          ], { x: 0.5, y: 1.5, w: '90%', fontSize: 18 });
        }

        const arrayBuffer = await pres.write({ outputType: 'arraybuffer' });
        const blob = new Blob([arrayBuffer as ArrayBuffer], { type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' });
        setGeneratedFile({ name: `${topic.replace(/\s+/g, '_')}.pptx`, blob });
      } else {
        const doc = new Document({
          sections: [{
            properties: {},
            children: [
              new Paragraph({
                text: topic.toUpperCase(),
                heading: HeadingLevel.TITLE,
              }),
              new Paragraph({
                children: [
                  new TextRun({
                    text: "Strategic Research Manifest",
                    bold: true,
                    color: "3b82f6",
                  }),
                ],
              }),
              new Paragraph({
                text: "Deep research synthesis generated on AI Clone global cluster.",
                spacing: { before: 400 },
              }),
              new Paragraph({
                text: "Abstract",
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400 },
              }),
              new Paragraph({
                text: "This document outlines the multi-dimensional analysis conducted on the specified topic, utilizing sovereign kernels for data verification.",
              }),
            ],
          }],
        });

        const blob = await Packer.toBlob(doc);
        setGeneratedFile({ name: `${topic.replace(/\s+/g, '_')}.docx`, blob });
      }
    } catch (e) {
      console.error(e);
    }

    setProgress(100);
    await new Promise(r => setTimeout(r, 500));
    setIsGenerating(false);
  };

  const handleDownload = () => {
    if (!generatedFile) return;
    const url = URL.createObjectURL(generatedFile.blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = generatedFile.name;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 overflow-y-auto p-8 lg:p-12 max-w-7xl mx-auto w-full space-y-12">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 pb-8 border-b border-border/40">
        <div className="space-y-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-foreground text-background">
              <Layers size={20} />
            </div>
            <h1 className="text-4xl font-black tracking-tighter text-foreground uppercase">Research Studio</h1>
          </div>
          <p className="text-muted-foreground/60 font-medium max-w-md leading-relaxed">
            Generate professional-grade presentations and manifests from your research data with autonomous layout engines.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
        {/* Input Column */}
        <div className="lg:col-span-2 space-y-8">
           <div className="flex gap-4 p-2 bg-foreground/5 rounded-[28px] border border-border/20">
              <button 
                onClick={() => setDocType('pptx')}
                className={cn(
                  "flex-1 h-14 rounded-2xl flex items-center justify-center gap-3 text-xs font-black uppercase tracking-widest transition-all",
                  docType === 'pptx' ? "bg-background text-foreground shadow-xl shadow-black/5" : "text-muted-foreground/60 hover:text-foreground"
                )}
              >
                <Presentation size={18} /> Presentation
              </button>
              <button 
                onClick={() => setDocType('docx')}
                className={cn(
                  "flex-1 h-14 rounded-2xl flex items-center justify-center gap-3 text-xs font-black uppercase tracking-widest transition-all",
                  docType === 'docx' ? "bg-background text-foreground shadow-xl shadow-black/5" : "text-muted-foreground/60 hover:text-foreground"
                )}
              >
                <FileText size={18} /> Manifest (Docx)
              </button>
           </div>

           <div className="space-y-4">
              <label className="text-[10px] font-black uppercase tracking-[0.4em] text-muted-foreground/40 px-2">Research Topic or Outline</label>
              <textarea 
                value={topic}
                onChange={e => setTopic(e.target.value)}
                placeholder="Enter topic, bullet points, or structured outline..."
                className="w-full h-48 p-8 bg-card/40  border border-border/40 rounded-3xl outline-none focus:border-foreground/20 focus:ring-8 focus:ring-foreground/[0.01] transition-all text-xl font-bold tracking-tight resize-none placeholder:text-muted-foreground/10"
              />
           </div>

           <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {[
                { id: 'professional', name: 'Professional', icon: Layout },
                { id: 'minimal', name: 'Minimalist', icon: Type },
                { id: 'dark', name: 'Dark Mode', icon: Monitor }
              ].map(t => (
                <button 
                  key={t.id}
                  onClick={() => setTemplate(t.id)}
                  className={cn(
                    "h-20 px-6 rounded-3xl border flex items-center gap-4 transition-all",
                    template === t.id ? "bg-primary/5 border-primary text-primary" : "bg-card/40 border-border/40 text-muted-foreground hover:border-foreground/20"
                  )}
                >
                  <t.icon size={20} />
                  <span className="text-xs font-black uppercase tracking-widest">{t.name}</span>
                </button>
              ))}
           </div>

           {/* Configuration Options */}
           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-4 p-6 bg-card/40 border border-border/40 text-foreground rounded-2xl">
                 <label className="text-[10px] font-black uppercase tracking-[0.4em] text-muted-foreground/60 block">Slide Count</label>
                 <div className="flex items-center gap-4">
                    <input 
                      type="range" 
                      min="1" max="25" 
                      value={slideCount} 
                      onChange={(e) => setSlideCount(parseInt(e.target.value))}
                      className="flex-1 accent-primary" 
                    />
                    <span className="text-xl font-bold w-8 text-right">{slideCount}</span>
                 </div>
              </div>
              <div className="space-y-4 p-6 bg-card/40 border border-border/40 rounded-2xl">
                 <label className="text-[10px] font-black uppercase tracking-[0.4em] text-muted-foreground/60 block">Accent Color</label>
                 <div className="flex items-center justify-between gap-2">
                    {[
                      { hex: '3b82f6', bg: 'bg-blue-500' }, // Blue
                      { hex: '10b981', bg: 'bg-emerald-500' }, // Emerald
                      { hex: '8b5cf6', bg: 'bg-violet-500' }, // Violet
                      { hex: 'f43f5e', bg: 'bg-rose-500' }, // Rose
                      { hex: 'f59e0b', bg: 'bg-amber-500' } // Amber
                    ].map(c => (
                      <button 
                        key={c.hex}
                        onClick={() => setThemeColor(c.hex)}
                        className={cn(
                          `w-8 h-8 rounded-full ${c.bg} transition-all border-4`,
                          themeColor === c.hex ? "border-foreground/20 scale-110 shadow-lg" : "border-transparent opacity-60 hover:opacity-100"
                        )}
                      />
                    ))}
                 </div>
              </div>
           </div>

           <button 
             disabled={!topic.trim() || isGenerating}
             onClick={handleGenerate}
             className="w-full h-20 bg-foreground text-background rounded-2xl font-black uppercase tracking-[0.2em] text-sm hover:opacity-90 active:scale-[0.98] transition-all flex items-center justify-center gap-4 shadow-2xl shadow-foreground/20 disabled:opacity-20 disabled:pointer-events-none"
           >
             {isGenerating ? (
               <RefreshCw size={24} className="animate-spin" />
             ) : (
               <>
                 <span>Initialize Production</span>
                 <Sparkles size={20} />
               </>
             )}
           </button>
        </div>

        {/* Status Column */}
        <div className="space-y-8">
           <div className="p-10 bg-card/40  border border-border/40 rounded-3xl flex flex-col items-center justify-center text-center min-h-[400px]">
              <AnimatePresence mode="wait">
                {isGenerating ? (
                   <motion.div 
                     key="generating"
                     initial={{ opacity: 0 }}
                     animate={{ opacity: 1 }}
                     exit={{ opacity: 0 }}
                     className="space-y-8 w-full"
                   >
                      <div className="w-24 h-24 rounded-full border-4 border-foreground/5 border-t-primary animate-spin mx-auto" />
                      <div className="space-y-2">
                        <div className="text-[10px] font-black uppercase tracking-[0.4em] text-primary">Compiling Manifest</div>
                        <div className="text-sm font-bold opacity-60">Phase {progress < 50 ? '1' : progress < 90 ? '2' : '3'}: Kernel Sync</div>
                        <div className="w-full h-1 bg-foreground/5 rounded-full mt-6 overflow-hidden">
                           <motion.div 
                             className="h-full bg-primary" 
                             initial={{ width: 0 }} 
                             animate={{ width: `${progress}%` }} 
                           />
                        </div>
                      </div>
                   </motion.div>
                ) : generatedFile ? (
                  <motion.div 
                     key="ready"
                     initial={{ scale: 0.9, opacity: 0 }}
                     animate={{ scale: 1, opacity: 1 }}
                     className="space-y-8 w-full"
                  >
                     <div className="w-24 h-24 rounded-3xl bg-green-500/10 flex items-center justify-center text-green-500 mx-auto shadow-2xl shadow-green-500/10 border border-green-500/20">
                        <CheckCircle2 size={48} />
                     </div>
                     <div className="space-y-2">
                        <h3 className="text-2xl font-black tracking-tighter uppercase leading-none">Manifest Staged</h3>
                        <p className="text-sm text-muted-foreground font-medium truncate px-4">{generatedFile.name}</p>
                     </div>
                     <div className="flex flex-col gap-3">
                        <button 
                          onClick={handleDownload}
                          className="h-14 bg-foreground text-background rounded-2xl font-black uppercase tracking-widest text-[10px] flex items-center justify-center gap-3 hover:opacity-90 transition-all"
                        >
                           <Download size={16} /> Deploy Manifest
                        </button>
                        <button 
                           className="h-14 border border-border/40 rounded-2xl font-black uppercase tracking-widest text-[10px] flex items-center justify-center gap-3 hover:bg-card transition-all"
                        >
                           <FileDown size={16} /> Export as PDF
                        </button>
                     </div>
                  </motion.div>
                ) : (
                  <motion.div 
                    key="idle"
                    className="space-y-6"
                  >
                     <Palette size={64} className="text-muted-foreground/10 mx-auto" />
                     <div className="space-y-2">
                        <h3 className="text-lg font-black tracking-tighter text-muted-foreground/20 uppercase">Awaiting Schema</h3>
                        <p className="text-sm text-muted-foreground/20 font-medium">Production pipeline idle. <br/> Initialize topic for deployment.</p>
                     </div>
                  </motion.div>
                )}
              </AnimatePresence>
           </div>
           
           <div className="p-8 bg-blue-500/5 border border-blue-500/10 rounded-3xl space-y-4">
              <div className="flex items-center gap-3 text-blue-500">
                 <Zap size={16} />
                 <span className="text-[10px] font-black uppercase tracking-[0.3em]">Pro Studio Capabilities</span>
              </div>
              <ul className="space-y-3">
                 {['Smart Layout Engine', 'Vector Icon Synthesis', 'Auto-Reference citations'].map((f, i) => (
                   <li key={i} className="flex items-center gap-3 text-xs font-bold text-muted-foreground/60">
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500/40" /> {f}
                   </li>
                 ))}
              </ul>
           </div>
        </div>
      </div>
    </div>
  );
}
