// ============================================================
// AI Clone — Export API Route
// POST /api/export
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { mdToText } from '@/lib/utils';

export async function POST(req: NextRequest) {
  const { content, format, title } = await req.json();

  if (!content || !format) {
    return NextResponse.json({ error: 'Missing content or format' }, { status: 400 });
  }

  if (format === 'markdown') {
    const markdown = `# ${title || 'AI Clone Research'}\n\n*Generated by AI Clone — ${new Date().toLocaleDateString()}*\n\n---\n\n${content}`;
    return new Response(markdown, {
      headers: {
        'Content-Type': 'text/markdown',
        'Content-Disposition': `attachment; filename="AI Clone-${Date.now()}.md"`,
      },
    });
  }

  if (format === 'text') {
    const text = `${title || 'AI Clone Research'}\n\n${mdToText(content)}`;
    return new Response(text, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="AI Clone-${Date.now()}.txt"`,
      },
    });
  }

  return NextResponse.json({ error: 'Unsupported format' }, { status: 400 });
}
